#!/bin/bash

#This Script is only used to handle Binary Installations.
#Build from Source is not handled here.
#This should run before the build from source.

#This is an initialization of an array
Programs=()

#This is for the ASUS related things
#source Asus_Specific.txt

#These are for the common package, and build tools gcc, yay, make
source Build_Tools.txt

#These are for specific works, like xflyer, freecad
source Engineering_Specific.txt

#These are just for fun terminal programs cowsay, pokeget
source Fun_Terminal_Prog.txt

#These are the calendars, communication, and browser
source General_Productivity.txt

#These are for image editing, sound, admin privileges sudo, and other apps
source Misc_User_Specific.txt

#These are some programing languages and libraries
source Programming_Libraries.txt

#These are for Ricing the System
source Ricing.txt

#These are for some very basic things about the system
source System_Packages.txt

#This is for the Latex Vim PDF toolchain
source Technical_Writing.txt

#This is just telling how much programs are going to be installed
echo "Number of Programs to Perform Binary Installation:" ${#Programs[@]}

#Command to Install the Programs
sudo pacman -Syu ${Programs[@]}
