#!/bin/bash

#Launchnew kitty terminal instances that listens for instructions
kitty --listen-on unix:/tmp/trml_01 & #Listen on tmp/tmrl_01
kitty --listen-on unix:/tmp/trml_02 & #Listen on tmp/tmrl_02
kitty --listen-on unix:/tmp/trml_03 & #Listen on tmp/tmrl_03

sleep 0.2
