#!/bin/bash

#This is a simple wrapper around the ffmpeg to allow us to record screen, lossy encoding and with audi

ffmpeg -f x11grab -video_size 1920x1080 -framerate 25 -i $DISPLAY -f alsa -i default -c:v libx264 -preset ultrafast -c:a aac $1
