#!/bin/bash

#This is to install the Rice specific dotfiles
cd Hidden_Files/ && ./Installs && cd ..
#This is to install the necessary programs
cd Prog_Install/ && ./Installs && cd ..
#This is to install the typicakl wallpapers
cd Wallpaper/ && ./Installs && cd ..
echo "Ricing Complete..."
