#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


############################################################

#Allow usage of user defined scripts
source ~/.bashrc

#Start the compactor
picom &

#Set the tint screen
redshift -P -O 4500

#To Allow Wallpaper
feh --no-fehbg --bg-max  $HOME/Archive_Drive/Wallpaper/Active/Frozen_Trees.jpg

#Start the Window Manager
#exec dwm
exec i3
#exec awesome
