#!/bin/bash

#This command produces a list of all files found with their line count, if you want to have the sum for all the files found, you can use find to list the files (with the -print option) and than use xargs to pass this list as argument to wc-l.

#find . -name "*.c" -print | xargs wc -l 

#EDIT to address Robert Gamble comment (thanks): if you have spaces or newlines (!) in file names, then you have to use -print0 option instead of -print and xargs -null so that the list of file names are exchanged with null-terminated strings.

#find . -name "*.c" -print0 | xargs -0 wc -l



#find . -name "*.c" -exec wc -l {} \;
#    . is the name of the top directory to start searching from
#    -name "*.c" is the pattern of the file you're interested in
#    -exec gives a command to be executed
#    {} is the result of the find command to be passed to the command (here wc-l)
#    \; indicates the end of the command

#First argument is the file extension we want
#Example: CodeCount *.py #Counts Python files recursively
find . -name "$1" -print | xargs wc -l
